# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8977619cf006edf6411f69fb78b77ee033987b9ea76c7c3b819a9848061b20ba5deb54cc2da6646e1fb646b065b350a8e1353f5cdf41cfdd22a65f4875ef16c

test:
  secret_key_base: 435ce27648e72d4efc6d416873a85f654d3e45523f2629ff84a9e853e12d352729325e6fa60013c42756fb0249ee940b5ae778be08e3b671d96f7e8788755490

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
